version: 2.1


jobs:
  deploy:
      docker:
        - image: circleci/python:3.6-jessie
      working_directory: ~/work
      steps:
        - checkout
        - run: 
            command: |
              pwd
              ls -ltr -a 

workflows:
  deploy:
    jobs:
      - deploy:
            filters:
                branches:
                  only: main
