version: 2.1


jobs:
  deploy:
      docker:
        - image: circleci/python:3.6-jessie
      working_directory: ~/
      steps:
        - checkout
        - run: 
            command: |
              ls -ltr

workflows:
  deploy:
    jobs:
      - deploy:
            filters:
                branches:
                  only: main
