version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  deploy:
      docker:
        - image: circleci/python:3.6-jessie
      working_directory: ~/PortfolioWebPage
      steps:
        - checkout
        - aws-cli/install
        - run:
            name: "authorize-security-group-ingress"
            command: |
              IP=`curl -s ifconfig.me`
              echo "#!/bin/bash" > ./sg.sh
              echo "aws ec2 authorize-security-group-ingress --group-id sg-0fd3983023d3016d5 --protocol tcp --port 22 --cidr ${IP}/32" >> ./sg.sh
              bash ./sg.sh
        - add_ssh_keys:
            fingerprints:
              - '07:29:e5:22:11:9c:c4:23:02:bb:aa:e6:93:cd:0c:6d'
        - run: scp -o StrictHostKeyChecking=no -r /home/circleci/PortfolioWebPage ${USER_NAME}@${HOST_NAME}:~
        - run: ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} 'sudo cp /home/chocopon1/PortfolioWebPage/* /var/www/html/ | sudo systemctl restart httpd'
        - run:
            name: "revoke-security-group-ingress"
            command: |
              IP=`curl -s ifconfig.me`
              echo "#!/bin/bash" > ./sg.sh
              echo "aws ec2 revoke-security-group-ingress --group-id sg-0fd3983023d3016d5 --protocol tcp --port 22 --cidr ${IP}/32" >> ./sg.sh
              bash ./sg.sh
workflows:
  deploy:
    jobs:
      - deploy:
            filters:
                branches:
                  only: main