version: 2.1


jobs:
  deploy:
      docker:
        - image: circleci/python:3.6-jessie
      working_directory: ~/PortfolioWebPage
      steps:
        - checkout
        - run: cd ..
        - run: ls ltr -a 

workflows:
  deploy:
    jobs:
      - deploy:
            filters:
                branches:
                  only: main
